package com.example.demo.pojo;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.total_pay
     *
     * @mbggenerated
     */
    private Long totalPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.actual_pay
     *
     * @mbggenerated
     */
    private Long actualPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.promotion_ids
     *
     * @mbggenerated
     */
    private String promotionIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.payment_type
     *
     * @mbggenerated
     */
    private Byte paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.post_fee
     *
     * @mbggenerated
     */
    private Long postFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.shipping_name
     *
     * @mbggenerated
     */
    private String shippingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.shipping_code
     *
     * @mbggenerated
     */
    private String shippingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.buyer_message
     *
     * @mbggenerated
     */
    private String buyerMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.buyer_nick
     *
     * @mbggenerated
     */
    private String buyerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.buyer_rate
     *
     * @mbggenerated
     */
    private Boolean buyerRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.receiver_state
     *
     * @mbggenerated
     */
    private String receiverState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.receiver_city
     *
     * @mbggenerated
     */
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.receiver_district
     *
     * @mbggenerated
     */
    private String receiverDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.receiver_address
     *
     * @mbggenerated
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.receiver_mobile
     *
     * @mbggenerated
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.receiver_zip
     *
     * @mbggenerated
     */
    private String receiverZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.receiver
     *
     * @mbggenerated
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.invoice_type
     *
     * @mbggenerated
     */
    private Integer invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.source_type
     *
     * @mbggenerated
     */
    private Integer sourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_id
     *
     * @return the value of tb_order.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_id
     *
     * @param orderId the value for tb_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.total_pay
     *
     * @return the value of tb_order.total_pay
     *
     * @mbggenerated
     */
    public Long getTotalPay() {
        return totalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.total_pay
     *
     * @param totalPay the value for tb_order.total_pay
     *
     * @mbggenerated
     */
    public void setTotalPay(Long totalPay) {
        this.totalPay = totalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.actual_pay
     *
     * @return the value of tb_order.actual_pay
     *
     * @mbggenerated
     */
    public Long getActualPay() {
        return actualPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.actual_pay
     *
     * @param actualPay the value for tb_order.actual_pay
     *
     * @mbggenerated
     */
    public void setActualPay(Long actualPay) {
        this.actualPay = actualPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.promotion_ids
     *
     * @return the value of tb_order.promotion_ids
     *
     * @mbggenerated
     */
    public String getPromotionIds() {
        return promotionIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.promotion_ids
     *
     * @param promotionIds the value for tb_order.promotion_ids
     *
     * @mbggenerated
     */
    public void setPromotionIds(String promotionIds) {
        this.promotionIds = promotionIds == null ? null : promotionIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.payment_type
     *
     * @return the value of tb_order.payment_type
     *
     * @mbggenerated
     */
    public Byte getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.payment_type
     *
     * @param paymentType the value for tb_order.payment_type
     *
     * @mbggenerated
     */
    public void setPaymentType(Byte paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.post_fee
     *
     * @return the value of tb_order.post_fee
     *
     * @mbggenerated
     */
    public Long getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.post_fee
     *
     * @param postFee the value for tb_order.post_fee
     *
     * @mbggenerated
     */
    public void setPostFee(Long postFee) {
        this.postFee = postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.create_time
     *
     * @return the value of tb_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.create_time
     *
     * @param createTime the value for tb_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.shipping_name
     *
     * @return the value of tb_order.shipping_name
     *
     * @mbggenerated
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.shipping_name
     *
     * @param shippingName the value for tb_order.shipping_name
     *
     * @mbggenerated
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.shipping_code
     *
     * @return the value of tb_order.shipping_code
     *
     * @mbggenerated
     */
    public String getShippingCode() {
        return shippingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.shipping_code
     *
     * @param shippingCode the value for tb_order.shipping_code
     *
     * @mbggenerated
     */
    public void setShippingCode(String shippingCode) {
        this.shippingCode = shippingCode == null ? null : shippingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.user_id
     *
     * @return the value of tb_order.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.user_id
     *
     * @param userId the value for tb_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.buyer_message
     *
     * @return the value of tb_order.buyer_message
     *
     * @mbggenerated
     */
    public String getBuyerMessage() {
        return buyerMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.buyer_message
     *
     * @param buyerMessage the value for tb_order.buyer_message
     *
     * @mbggenerated
     */
    public void setBuyerMessage(String buyerMessage) {
        this.buyerMessage = buyerMessage == null ? null : buyerMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.buyer_nick
     *
     * @return the value of tb_order.buyer_nick
     *
     * @mbggenerated
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.buyer_nick
     *
     * @param buyerNick the value for tb_order.buyer_nick
     *
     * @mbggenerated
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.buyer_rate
     *
     * @return the value of tb_order.buyer_rate
     *
     * @mbggenerated
     */
    public Boolean getBuyerRate() {
        return buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.buyer_rate
     *
     * @param buyerRate the value for tb_order.buyer_rate
     *
     * @mbggenerated
     */
    public void setBuyerRate(Boolean buyerRate) {
        this.buyerRate = buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receiver_state
     *
     * @return the value of tb_order.receiver_state
     *
     * @mbggenerated
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receiver_state
     *
     * @param receiverState the value for tb_order.receiver_state
     *
     * @mbggenerated
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState == null ? null : receiverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receiver_city
     *
     * @return the value of tb_order.receiver_city
     *
     * @mbggenerated
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receiver_city
     *
     * @param receiverCity the value for tb_order.receiver_city
     *
     * @mbggenerated
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receiver_district
     *
     * @return the value of tb_order.receiver_district
     *
     * @mbggenerated
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receiver_district
     *
     * @param receiverDistrict the value for tb_order.receiver_district
     *
     * @mbggenerated
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receiver_address
     *
     * @return the value of tb_order.receiver_address
     *
     * @mbggenerated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receiver_address
     *
     * @param receiverAddress the value for tb_order.receiver_address
     *
     * @mbggenerated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receiver_mobile
     *
     * @return the value of tb_order.receiver_mobile
     *
     * @mbggenerated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receiver_mobile
     *
     * @param receiverMobile the value for tb_order.receiver_mobile
     *
     * @mbggenerated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receiver_zip
     *
     * @return the value of tb_order.receiver_zip
     *
     * @mbggenerated
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receiver_zip
     *
     * @param receiverZip the value for tb_order.receiver_zip
     *
     * @mbggenerated
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receiver
     *
     * @return the value of tb_order.receiver
     *
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receiver
     *
     * @param receiver the value for tb_order.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.invoice_type
     *
     * @return the value of tb_order.invoice_type
     *
     * @mbggenerated
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.invoice_type
     *
     * @param invoiceType the value for tb_order.invoice_type
     *
     * @mbggenerated
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.source_type
     *
     * @return the value of tb_order.source_type
     *
     * @mbggenerated
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.source_type
     *
     * @param sourceType the value for tb_order.source_type
     *
     * @mbggenerated
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }
}